sudo: required
services:
    - docker

before_install:
    - docker build -t adityaraval/docker-react-ci -f Dockerfile.dev .

script:
    - docker run -e CI=true adityaraval/docker-react-ci npm run test

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "docker-react-ci"
    env: "DockerReactCi-env"
    bucket_name: "elasticbeanstalk-ap-south-1-762385662695"
    bucket_path: "docker-react-ci"
    on:
        branch: master
        access_key_id:
            secure: "$AWS_ACCESS_KEY"
        secret_access_key:
            secure: "$AWS_SECRET_KEY"
