sudo: required
services:
    - docker

before_install:
    - docker build -t adityaraval/docker-react-ci -f Dockerfile.dev .

script:
    - docker run adityaraval/docker-react-ci npm run test -- --coverage